name: Secure Java Crypto

on : push

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: 1mansis/javacrypto:latest
          build-args: |
            arg1=value1
            arg2=value2
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

#jobs:
#  main:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: docker/build-push-action@v2
#        name: Pushing to Docker Hub
#        with:
#          push: true
#          #image: 1mansis/javacrypto
#          tags: 1mansis/javacrypto:latest
#          registry: hub.docker.com
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_PASSWORD }}
