name: Secure Java Crypto

on : push

jobs:
  build:
    - uses: actions/checkout@v2
    - uses: docker/setup-buildx-action@v1
      with:
        driver: docker
    - uses: docker/login-action@v1
      with:
        registry: hub.docker.com
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - uses: docker/build-push-action@v2
      with:
        context: .
        tags: 1mansis/javacrypto:latest
        load: true
    - run: docker push hub.docker.com/1mansis/javacrypto:latest

#jobs:
#  main:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: docker/build-push-action@v2
#        name: Pushing to Docker Hub
#        with:
#          push: true
#          #image: 1mansis/javacrypto
#          tags: 1mansis/javacrypto:latest
#          registry: hub.docker.com
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_PASSWORD }}
